apiVersion: v1
kind: Service
metadata:
  name: {{ include "ogc-headscale.fullname" . }}
  labels:
    {{- include "ogc-headscale.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.grpc.port }}
      protocol: TCP
      name: grpc
  selector:
    {{- include "ogc-headscale.selectorLabels" . | nindent 4 }}
