---
name: Release Docker

on:
  push:
    tags:
      - "*" # triggers only if push new tag version
  workflow_dispatch:

jobs:
  get-version:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.get-version.outputs.app_version }}
    steps:
      - name: Get version
        id: get-version
        run: |
          echo "app_version=${GITHUB_REF#refs/tags/}" | cut -c2- >> $GITHUB_OUTPUT 

  docker-release:
    uses: ori-edge/oge-github-actions/.github/workflows/docker.yml@v0.10.0
    needs: get-version
    with:
      dockerImageMode: custom
      imageName: headscale
      imageVersion: ${{ needs.get-version.outputs.version }}
      push: ${{ github.actor != 'dependabot[bot]' }}
    secrets:
      REGISTRY_USERNAME: ${{ secrets.QUAY_USERNAME }}
      REGISTRY_PASSWORD: ${{ secrets.QUAY_PASSWORD }}